[project]
name = "ssh_honeypot"
version = "0.1.0"
dependencies = ["paramiko == 3.4"]

[build-system]
requires = ["setuptools == 71.1.0"]
build-backend = "setuptools.build_meta"

[project.scripts]
ssh-honeypot = "ssh_honeypot.app:main"
